package dev.com.matricula.model;

// Generated 02/02/2014 11:46:24 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Anhoescolar generated by hbm2java
 */
public class AnhoEscolar implements java.io.Serializable {

  private String idAnhoEscolar;
  private Date fechaInicial;
  private Date fechaFinal;
  private char estado;
  private Integer codUsuario;
  private Date fechaOperacion;
  private Set matriculas = new HashSet(0);
  private Set horarios = new HashSet(0);
  private Set asignacions = new HashSet(0);

  public AnhoEscolar() {
  }

  public AnhoEscolar(String idAnhoEscolar, Date fechaInicial, Date fechaFinal, char estado) {
    this.idAnhoEscolar = idAnhoEscolar;
    this.fechaInicial = fechaInicial;
    this.fechaFinal = fechaFinal;
    this.estado = estado;
  }

  public AnhoEscolar(String idAnhoEscolar, Date fechaInicial, Date fechaFinal, char estado,
          Integer codUsuario, Date fechaOperacion, Set matriculas, Set horarios, Set asignacions) {
    this.idAnhoEscolar = idAnhoEscolar;
    this.fechaInicial = fechaInicial;
    this.fechaFinal = fechaFinal;
    this.estado = estado;
    this.codUsuario = codUsuario;
    this.fechaOperacion = fechaOperacion;
    this.matriculas = matriculas;
    this.horarios = horarios;
    this.asignacions = asignacions;
  }

  public String getIdAnhoEscolar() {
    return this.idAnhoEscolar;
  }

  public void setIdAnhoEscolar(String idAnhoEscolar) {
    this.idAnhoEscolar = idAnhoEscolar;
  }

  public Date getFechaInicial() {
    return this.fechaInicial;
  }

  public void setFechaInicial(Date fechaInicial) {
    this.fechaInicial = fechaInicial;
  }

  public Date getFechaFinal() {
    return this.fechaFinal;
  }

  public void setFechaFinal(Date fechaFinal) {
    this.fechaFinal = fechaFinal;
  }

  public char getEstado() {
    return this.estado;
  }

  public void setEstado(char estado) {
    this.estado = estado;
  }

  public Integer getCodUsuario() {
    return this.codUsuario;
  }

  public void setCodUsuario(Integer codUsuario) {
    this.codUsuario = codUsuario;
  }

  public Date getFechaOperacion() {
    return this.fechaOperacion;
  }

  public void setFechaOperacion(Date fechaOperacion) {
    this.fechaOperacion = fechaOperacion;
  }

  public Set getMatriculas() {
    return this.matriculas;
  }

  public void setMatriculas(Set matriculas) {
    this.matriculas = matriculas;
  }

  public Set getHorarios() {
    return this.horarios;
  }

  public void setHorarios(Set horarios) {
    this.horarios = horarios;
  }

  public Set getAsignacions() {
    return this.asignacions;
  }

  public void setAsignacions(Set asignacions) {
    this.asignacions = asignacions;
  }

}
