package dev.com.matricula.model;

// Generated 02/02/2014 11:46:24 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * AsignacionId generated by hbm2java
 */
public class AsignacionId implements java.io.Serializable {

  private char seccion;
  private String idDocente;
  private String idCurso;
  private String idAnhoEscolar;
  private Integer codUsuario;
  private Date fechaOperacion;

  public AsignacionId() {
  }

  public AsignacionId(char seccion, String idDocente, String idCurso, String idAnhoEscolar) {
    this.seccion = seccion;
    this.idDocente = idDocente;
    this.idCurso = idCurso;
    this.idAnhoEscolar = idAnhoEscolar;
  }

  public AsignacionId(char seccion, String idDocente, String idCurso, String idAnhoEscolar,
          Integer codUsuario, Date fechaOperacion) {
    this.seccion = seccion;
    this.idDocente = idDocente;
    this.idCurso = idCurso;
    this.idAnhoEscolar = idAnhoEscolar;
    this.codUsuario = codUsuario;
    this.fechaOperacion = fechaOperacion;
  }

  public char getSeccion() {
    return this.seccion;
  }

  public void setSeccion(char seccion) {
    this.seccion = seccion;
  }

  public String getIdDocente() {
    return this.idDocente;
  }

  public void setIdDocente(String idDocente) {
    this.idDocente = idDocente;
  }

  public String getIdCurso() {
    return this.idCurso;
  }

  public void setIdCurso(String idCurso) {
    this.idCurso = idCurso;
  }

  public String getIdAnhoEscolar() {
    return this.idAnhoEscolar;
  }

  public void setIdAnhoEscolar(String idAnhoEscolar) {
    this.idAnhoEscolar = idAnhoEscolar;
  }

  public Integer getCodUsuario() {
    return this.codUsuario;
  }

  public void setCodUsuario(Integer codUsuario) {
    this.codUsuario = codUsuario;
  }

  public Date getFechaOperacion() {
    return this.fechaOperacion;
  }

  public void setFechaOperacion(Date fechaOperacion) {
    this.fechaOperacion = fechaOperacion;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof AsignacionId))
      return false;
    AsignacionId castOther = (AsignacionId) other;

    return (this.getSeccion() == castOther.getSeccion())
            && ((this.getIdDocente() == castOther.getIdDocente()) || (this.getIdDocente() != null
                    && castOther.getIdDocente() != null && this.getIdDocente().equals(
                    castOther.getIdDocente())))
            && ((this.getIdCurso() == castOther.getIdCurso()) || (this.getIdCurso() != null
                    && castOther.getIdCurso() != null && this.getIdCurso().equals(
                    castOther.getIdCurso())))
            && ((this.getIdAnhoEscolar() == castOther.getIdAnhoEscolar()) || (this
                    .getIdAnhoEscolar() != null && castOther.getIdAnhoEscolar() != null && this
                    .getIdAnhoEscolar().equals(castOther.getIdAnhoEscolar())))
            && ((this.getCodUsuario() == castOther.getCodUsuario()) || (this.getCodUsuario() != null
                    && castOther.getCodUsuario() != null && this.getCodUsuario().equals(
                    castOther.getCodUsuario())))
            && ((this.getFechaOperacion() == castOther.getFechaOperacion()) || (this
                    .getFechaOperacion() != null && castOther.getFechaOperacion() != null && this
                    .getFechaOperacion().equals(castOther.getFechaOperacion())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + this.getSeccion();
    result = 37 * result + (getIdDocente() == null ? 0 : this.getIdDocente().hashCode());
    result = 37 * result + (getIdCurso() == null ? 0 : this.getIdCurso().hashCode());
    result = 37 * result + (getIdAnhoEscolar() == null ? 0 : this.getIdAnhoEscolar().hashCode());
    result = 37 * result + (getCodUsuario() == null ? 0 : this.getCodUsuario().hashCode());
    result = 37 * result + (getFechaOperacion() == null ? 0 : this.getFechaOperacion().hashCode());
    return result;
  }

}
