package dev.com.matricula.model;

// Generated 02/02/2014 11:46:24 AM by Hibernate Tools 4.0.0

/**
 * Asignacion generated by hbm2java
 */
public class Asignacion implements java.io.Serializable {

  private AsignacionId id;
  private Docente docente;
  private Curso curso;
  private AnhoEscolar anhoescolar;

  public Asignacion() {
  }

  public Asignacion(AsignacionId id, Docente docente, Curso curso, AnhoEscolar anhoescolar) {
    this.id = id;
    this.docente = docente;
    this.curso = curso;
    this.anhoescolar = anhoescolar;
  }

  public AsignacionId getId() {
    return this.id;
  }

  public void setId(AsignacionId id) {
    this.id = id;
  }

  public Docente getDocente() {
    return this.docente;
  }

  public void setDocente(Docente docente) {
    this.docente = docente;
  }

  public Curso getCurso() {
    return this.curso;
  }

  public void setCurso(Curso curso) {
    this.curso = curso;
  }

  public AnhoEscolar getAnhoescolar() {
    return this.anhoescolar;
  }

  public void setAnhoescolar(AnhoEscolar anhoescolar) {
    this.anhoescolar = anhoescolar;
  }

}
