package dev.com.matricula.model;

// Generated 28/02/2014 12:15:27 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Aula generated by hbm2java
 */
public class Aula implements java.io.Serializable {

  private int idAula;
  private String tipo;
  private short capacidad;
  private Integer codUsuario;
  private Date fechaOperacion;
  private Set horarios = new HashSet(0);

  public Aula() {
  }

  public Aula(int idAula, String tipo, short capacidad) {
    this.idAula = idAula;
    this.tipo = tipo;
    this.capacidad = capacidad;
  }

  public Aula(int idAula, String tipo, short capacidad, Integer codUsuario, Date fechaOperacion,
          Set horarios) {
    this.idAula = idAula;
    this.tipo = tipo;
    this.capacidad = capacidad;
    this.codUsuario = codUsuario;
    this.fechaOperacion = fechaOperacion;
    this.horarios = horarios;
  }

  public int getIdAula() {
    return this.idAula;
  }

  public void setIdAula(int idAula) {
    this.idAula = idAula;
  }

  public String getTipo() {
    return this.tipo;
  }

  public void setTipo(String tipo) {
    this.tipo = tipo;
  }

  public short getCapacidad() {
    return this.capacidad;
  }

  public void setCapacidad(short capacidad) {
    this.capacidad = capacidad;
  }

  public Integer getCodUsuario() {
    return this.codUsuario;
  }

  public void setCodUsuario(Integer codUsuario) {
    this.codUsuario = codUsuario;
  }

  public Date getFechaOperacion() {
    return this.fechaOperacion;
  }

  public void setFechaOperacion(Date fechaOperacion) {
    this.fechaOperacion = fechaOperacion;
  }

  public Set getHorarios() {
    return this.horarios;
  }

  public void setHorarios(Set horarios) {
    this.horarios = horarios;
  }

}
