package dev.com.matricula.model;

// Generated 28/02/2014 12:15:27 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Colegio generated by hbm2java
 */
public class Colegio implements java.io.Serializable {

  private String idColegio;
  private String nombre;
  private String direccion;
  private char tipo;
  private Integer codUsuario;
  private Date fechaOperacion;
  private Set matriculas = new HashSet(0);

  public Colegio() {
  }

  public Colegio(String idColegio, String nombre, String direccion, char tipo) {
    this.idColegio = idColegio;
    this.nombre = nombre;
    this.direccion = direccion;
    this.tipo = tipo;
  }

  public Colegio(String idColegio, String nombre, String direccion, char tipo, Integer codUsuario,
          Date fechaOperacion, Set matriculas) {
    this.idColegio = idColegio;
    this.nombre = nombre;
    this.direccion = direccion;
    this.tipo = tipo;
    this.codUsuario = codUsuario;
    this.fechaOperacion = fechaOperacion;
    this.matriculas = matriculas;
  }

  public String getIdColegio() {
    return this.idColegio;
  }

  public void setIdColegio(String idColegio) {
    this.idColegio = idColegio;
  }

  public String getNombre() {
    return this.nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public String getDireccion() {
    return this.direccion;
  }

  public void setDireccion(String direccion) {
    this.direccion = direccion;
  }

  public char getTipo() {
    return this.tipo;
  }

  public void setTipo(char tipo) {
    this.tipo = tipo;
  }

  public Integer getCodUsuario() {
    return this.codUsuario;
  }

  public void setCodUsuario(Integer codUsuario) {
    this.codUsuario = codUsuario;
  }

  public Date getFechaOperacion() {
    return this.fechaOperacion;
  }

  public void setFechaOperacion(Date fechaOperacion) {
    this.fechaOperacion = fechaOperacion;
  }

  public Set getMatriculas() {
    return this.matriculas;
  }

  public void setMatriculas(Set matriculas) {
    this.matriculas = matriculas;
  }

}
