package dev.com.matricula.model;

// Generated 02/02/2014 11:46:24 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

  private String idCurso;
  private String nombreCurso;
  private short horasTeoricas;
  private short horasPracticas;
  private char nivel;
  private char grado;
  private Integer codUsuario;
  private Date fechaOperacion;
  private Set notases = new HashSet(0);
  private Set promedios = new HashSet(0);
  private Set horarios = new HashSet(0);
  private Set asignacions = new HashSet(0);

  public Curso() {
  }

  public Curso(String idCurso, String nombreCurso, short horasTeoricas, short horasPracticas,
          char nivel, char grado) {
    this.idCurso = idCurso;
    this.nombreCurso = nombreCurso;
    this.horasTeoricas = horasTeoricas;
    this.horasPracticas = horasPracticas;
    this.nivel = nivel;
    this.grado = grado;
  }

  public Curso(String idCurso, String nombreCurso, short horasTeoricas, short horasPracticas,
          char nivel, char grado, Integer codUsuario, Date fechaOperacion, Set notases,
          Set promedios, Set horarios, Set asignacions) {
    this.idCurso = idCurso;
    this.nombreCurso = nombreCurso;
    this.horasTeoricas = horasTeoricas;
    this.horasPracticas = horasPracticas;
    this.nivel = nivel;
    this.grado = grado;
    this.codUsuario = codUsuario;
    this.fechaOperacion = fechaOperacion;
    this.notases = notases;
    this.promedios = promedios;
    this.horarios = horarios;
    this.asignacions = asignacions;
  }

  public String getIdCurso() {
    return this.idCurso;
  }

  public void setIdCurso(String idCurso) {
    this.idCurso = idCurso;
  }

  public String getNombreCurso() {
    return this.nombreCurso;
  }

  public void setNombreCurso(String nombreCurso) {
    this.nombreCurso = nombreCurso;
  }

  public short getHorasTeoricas() {
    return this.horasTeoricas;
  }

  public void setHorasTeoricas(short horasTeoricas) {
    this.horasTeoricas = horasTeoricas;
  }

  public short getHorasPracticas() {
    return this.horasPracticas;
  }

  public void setHorasPracticas(short horasPracticas) {
    this.horasPracticas = horasPracticas;
  }

  public char getNivel() {
    return this.nivel;
  }

  public void setNivel(char nivel) {
    this.nivel = nivel;
  }

  public char getGrado() {
    return this.grado;
  }

  public void setGrado(char grado) {
    this.grado = grado;
  }

  public Integer getCodUsuario() {
    return this.codUsuario;
  }

  public void setCodUsuario(Integer codUsuario) {
    this.codUsuario = codUsuario;
  }

  public Date getFechaOperacion() {
    return this.fechaOperacion;
  }

  public void setFechaOperacion(Date fechaOperacion) {
    this.fechaOperacion = fechaOperacion;
  }

  public Set getNotases() {
    return this.notases;
  }

  public void setNotases(Set notases) {
    this.notases = notases;
  }

  public Set getPromedios() {
    return this.promedios;
  }

  public void setPromedios(Set promedios) {
    this.promedios = promedios;
  }

  public Set getHorarios() {
    return this.horarios;
  }

  public void setHorarios(Set horarios) {
    this.horarios = horarios;
  }

  public Set getAsignacions() {
    return this.asignacions;
  }

  public void setAsignacions(Set asignacions) {
    this.asignacions = asignacions;
  }

}
