package dev.com.matricula.model;

// Generated 28/02/2014 12:15:27 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Docente generated by hbm2java
 */
public class Docente implements java.io.Serializable {

  private int idDocente;
  private String nombre;
  private String apPaterno;
  private String apMaterno;
  private String direccion;
  private String telefono;
  private String dni;
  private String especialidad;
  private String email;
  private char sexo;
  private Integer codUsuario;
  private Date fechaOperacion;
  private Set horarios = new HashSet(0);
  private Set asignacions = new HashSet(0);

  public Docente() {
  }

  public Docente(int idDocente, String nombre, String apPaterno, String apMaterno, String dni,
          String especialidad, char sexo) {
    this.idDocente = idDocente;
    this.nombre = nombre;
    this.apPaterno = apPaterno;
    this.apMaterno = apMaterno;
    this.dni = dni;
    this.especialidad = especialidad;
    this.sexo = sexo;
  }

  public Docente(int idDocente, String nombre, String apPaterno, String apMaterno,
          String direccion, String telefono, String dni, String especialidad, String email,
          char sexo, Integer codUsuario, Date fechaOperacion, Set horarios, Set asignacions) {
    this.idDocente = idDocente;
    this.nombre = nombre;
    this.apPaterno = apPaterno;
    this.apMaterno = apMaterno;
    this.direccion = direccion;
    this.telefono = telefono;
    this.dni = dni;
    this.especialidad = especialidad;
    this.email = email;
    this.sexo = sexo;
    this.codUsuario = codUsuario;
    this.fechaOperacion = fechaOperacion;
    this.horarios = horarios;
    this.asignacions = asignacions;
  }

  public int getIdDocente() {
    return this.idDocente;
  }

  public void setIdDocente(int idDocente) {
    this.idDocente = idDocente;
  }

  public String getNombre() {
    return this.nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public String getApPaterno() {
    return this.apPaterno;
  }

  public void setApPaterno(String apPaterno) {
    this.apPaterno = apPaterno;
  }

  public String getApMaterno() {
    return this.apMaterno;
  }

  public void setApMaterno(String apMaterno) {
    this.apMaterno = apMaterno;
  }

  public String getDireccion() {
    return this.direccion;
  }

  public void setDireccion(String direccion) {
    this.direccion = direccion;
  }

  public String getTelefono() {
    return this.telefono;
  }

  public void setTelefono(String telefono) {
    this.telefono = telefono;
  }

  public String getDni() {
    return this.dni;
  }

  public void setDni(String dni) {
    this.dni = dni;
  }

  public String getEspecialidad() {
    return this.especialidad;
  }

  public void setEspecialidad(String especialidad) {
    this.especialidad = especialidad;
  }

  public String getEmail() {
    return this.email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public char getSexo() {
    return this.sexo;
  }

  public void setSexo(char sexo) {
    this.sexo = sexo;
  }

  public Integer getCodUsuario() {
    return this.codUsuario;
  }

  public void setCodUsuario(Integer codUsuario) {
    this.codUsuario = codUsuario;
  }

  public Date getFechaOperacion() {
    return this.fechaOperacion;
  }

  public void setFechaOperacion(Date fechaOperacion) {
    this.fechaOperacion = fechaOperacion;
  }

  public Set getHorarios() {
    return this.horarios;
  }

  public void setHorarios(Set horarios) {
    this.horarios = horarios;
  }

  public Set getAsignacions() {
    return this.asignacions;
  }

  public void setAsignacions(Set asignacions) {
    this.asignacions = asignacions;
  }

}
