package dev.com.matricula.model;

// Generated 28/02/2014 12:15:27 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Horario generated by hbm2java
 */
public class Horario implements java.io.Serializable {

  private int idHorario;
  private Docente docente;
  private Aula aula;
  private Curso curso;
  private Anhoescolar anhoescolar;
  private String dia;
  private Date horaInicial;
  private Date horaFinal;
  private Integer codUsuario;
  private Date fechaOperacion;

  public Horario() {
  }

  public Horario(int idHorario, Docente docente, Aula aula, Curso curso, Anhoescolar anhoescolar,
          String dia, Date horaInicial, Date horaFinal) {
    this.idHorario = idHorario;
    this.docente = docente;
    this.aula = aula;
    this.curso = curso;
    this.anhoescolar = anhoescolar;
    this.dia = dia;
    this.horaInicial = horaInicial;
    this.horaFinal = horaFinal;
  }

  public Horario(int idHorario, Docente docente, Aula aula, Curso curso, Anhoescolar anhoescolar,
          String dia, Date horaInicial, Date horaFinal, Integer codUsuario, Date fechaOperacion) {
    this.idHorario = idHorario;
    this.docente = docente;
    this.aula = aula;
    this.curso = curso;
    this.anhoescolar = anhoescolar;
    this.dia = dia;
    this.horaInicial = horaInicial;
    this.horaFinal = horaFinal;
    this.codUsuario = codUsuario;
    this.fechaOperacion = fechaOperacion;
  }

  public int getIdHorario() {
    return this.idHorario;
  }

  public void setIdHorario(int idHorario) {
    this.idHorario = idHorario;
  }

  public Docente getDocente() {
    return this.docente;
  }

  public void setDocente(Docente docente) {
    this.docente = docente;
  }

  public Aula getAula() {
    return this.aula;
  }

  public void setAula(Aula aula) {
    this.aula = aula;
  }

  public Curso getCurso() {
    return this.curso;
  }

  public void setCurso(Curso curso) {
    this.curso = curso;
  }

  public Anhoescolar getAnhoescolar() {
    return this.anhoescolar;
  }

  public void setAnhoescolar(Anhoescolar anhoescolar) {
    this.anhoescolar = anhoescolar;
  }

  public String getDia() {
    return this.dia;
  }

  public void setDia(String dia) {
    this.dia = dia;
  }

  public Date getHoraInicial() {
    return this.horaInicial;
  }

  public void setHoraInicial(Date horaInicial) {
    this.horaInicial = horaInicial;
  }

  public Date getHoraFinal() {
    return this.horaFinal;
  }

  public void setHoraFinal(Date horaFinal) {
    this.horaFinal = horaFinal;
  }

  public Integer getCodUsuario() {
    return this.codUsuario;
  }

  public void setCodUsuario(Integer codUsuario) {
    this.codUsuario = codUsuario;
  }

  public Date getFechaOperacion() {
    return this.fechaOperacion;
  }

  public void setFechaOperacion(Date fechaOperacion) {
    this.fechaOperacion = fechaOperacion;
  }

}
