package dev.com.matricula.model;

// Generated 28/02/2014 12:15:27 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Matricula generated by hbm2java
 */
public class Matricula implements java.io.Serializable {

  private int idMatricula;
  private Colegio colegio;
  private Alumno alumno;
  private Apoderado apoderado;
  private Anhoescolar anhoescolar;
  private Date fechaMatricula;
  private Date horaMatricula;
  private char nivel;
  private char grado;
  private char seccion;
  private char turno;
  private String situacion;
  private char estado;
  private String observacion;
  private Integer codUsuario;
  private Date fechaOperacion;

  public Matricula() {
  }

  public Matricula(int idMatricula, Colegio colegio, Alumno alumno, Apoderado apoderado,
          Anhoescolar anhoescolar, Date fechaMatricula, Date horaMatricula, char nivel, char grado,
          char seccion, char turno, char estado) {
    this.idMatricula = idMatricula;
    this.colegio = colegio;
    this.alumno = alumno;
    this.apoderado = apoderado;
    this.anhoescolar = anhoescolar;
    this.fechaMatricula = fechaMatricula;
    this.horaMatricula = horaMatricula;
    this.nivel = nivel;
    this.grado = grado;
    this.seccion = seccion;
    this.turno = turno;
    this.estado = estado;
  }

  public Matricula(int idMatricula, Colegio colegio, Alumno alumno, Apoderado apoderado,
          Anhoescolar anhoescolar, Date fechaMatricula, Date horaMatricula, char nivel, char grado,
          char seccion, char turno, String situacion, char estado, String observacion,
          Integer codUsuario, Date fechaOperacion) {
    this.idMatricula = idMatricula;
    this.colegio = colegio;
    this.alumno = alumno;
    this.apoderado = apoderado;
    this.anhoescolar = anhoescolar;
    this.fechaMatricula = fechaMatricula;
    this.horaMatricula = horaMatricula;
    this.nivel = nivel;
    this.grado = grado;
    this.seccion = seccion;
    this.turno = turno;
    this.situacion = situacion;
    this.estado = estado;
    this.observacion = observacion;
    this.codUsuario = codUsuario;
    this.fechaOperacion = fechaOperacion;
  }

  public int getIdMatricula() {
    return this.idMatricula;
  }

  public void setIdMatricula(int idMatricula) {
    this.idMatricula = idMatricula;
  }

  public Colegio getColegio() {
    return this.colegio;
  }

  public void setColegio(Colegio colegio) {
    this.colegio = colegio;
  }

  public Alumno getAlumno() {
    return this.alumno;
  }

  public void setAlumno(Alumno alumno) {
    this.alumno = alumno;
  }

  public Apoderado getApoderado() {
    return this.apoderado;
  }

  public void setApoderado(Apoderado apoderado) {
    this.apoderado = apoderado;
  }

  public Anhoescolar getAnhoescolar() {
    return this.anhoescolar;
  }

  public void setAnhoescolar(Anhoescolar anhoescolar) {
    this.anhoescolar = anhoescolar;
  }

  public Date getFechaMatricula() {
    return this.fechaMatricula;
  }

  public void setFechaMatricula(Date fechaMatricula) {
    this.fechaMatricula = fechaMatricula;
  }

  public Date getHoraMatricula() {
    return this.horaMatricula;
  }

  public void setHoraMatricula(Date horaMatricula) {
    this.horaMatricula = horaMatricula;
  }

  public char getNivel() {
    return this.nivel;
  }

  public void setNivel(char nivel) {
    this.nivel = nivel;
  }

  public char getGrado() {
    return this.grado;
  }

  public void setGrado(char grado) {
    this.grado = grado;
  }

  public char getSeccion() {
    return this.seccion;
  }

  public void setSeccion(char seccion) {
    this.seccion = seccion;
  }

  public char getTurno() {
    return this.turno;
  }

  public void setTurno(char turno) {
    this.turno = turno;
  }

  public String getSituacion() {
    return this.situacion;
  }

  public void setSituacion(String situacion) {
    this.situacion = situacion;
  }

  public char getEstado() {
    return this.estado;
  }

  public void setEstado(char estado) {
    this.estado = estado;
  }

  public String getObservacion() {
    return this.observacion;
  }

  public void setObservacion(String observacion) {
    this.observacion = observacion;
  }

  public Integer getCodUsuario() {
    return this.codUsuario;
  }

  public void setCodUsuario(Integer codUsuario) {
    this.codUsuario = codUsuario;
  }

  public Date getFechaOperacion() {
    return this.fechaOperacion;
  }

  public void setFechaOperacion(Date fechaOperacion) {
    this.fechaOperacion = fechaOperacion;
  }

}
