package dev.com.matricula.model;

// Generated 02/02/2014 11:46:24 AM by Hibernate Tools 4.0.0

/**
 * Notas generated by hbm2java
 */
public class Notas implements java.io.Serializable {

  private NotasId id;
  private Curso curso;
  private Alumno alumno;

  public Notas() {
  }

  public Notas(NotasId id, Curso curso, Alumno alumno) {
    this.id = id;
    this.curso = curso;
    this.alumno = alumno;
  }

  public NotasId getId() {
    return this.id;
  }

  public void setId(NotasId id) {
    this.id = id;
  }

  public Curso getCurso() {
    return this.curso;
  }

  public void setCurso(Curso curso) {
    this.curso = curso;
  }

  public Alumno getAlumno() {
    return this.alumno;
  }

  public void setAlumno(Alumno alumno) {
    this.alumno = alumno;
  }

}
