package dev.com.matricula.model;

// Generated 28/02/2014 12:15:27 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Parentesco generated by hbm2java
 */
public class Parentesco implements java.io.Serializable {

  private int idParentesco;
  private Alumno alumno;
  private Apoderado apoderado;
  private String parentesco;
  private Integer codUsuario;
  private Date fechaOperacion;

  public Parentesco() {
  }

  public Parentesco(int idParentesco, Alumno alumno, Apoderado apoderado, String parentesco) {
    this.idParentesco = idParentesco;
    this.alumno = alumno;
    this.apoderado = apoderado;
    this.parentesco = parentesco;
  }

  public Parentesco(int idParentesco, Alumno alumno, Apoderado apoderado, String parentesco,
          Integer codUsuario, Date fechaOperacion) {
    this.idParentesco = idParentesco;
    this.alumno = alumno;
    this.apoderado = apoderado;
    this.parentesco = parentesco;
    this.codUsuario = codUsuario;
    this.fechaOperacion = fechaOperacion;
  }

  public int getIdParentesco() {
    return this.idParentesco;
  }

  public void setIdParentesco(int idParentesco) {
    this.idParentesco = idParentesco;
  }

  public Alumno getAlumno() {
    return this.alumno;
  }

  public void setAlumno(Alumno alumno) {
    this.alumno = alumno;
  }

  public Apoderado getApoderado() {
    return this.apoderado;
  }

  public void setApoderado(Apoderado apoderado) {
    this.apoderado = apoderado;
  }

  public String getParentesco() {
    return this.parentesco;
  }

  public void setParentesco(String parentesco) {
    this.parentesco = parentesco;
  }

  public Integer getCodUsuario() {
    return this.codUsuario;
  }

  public void setCodUsuario(Integer codUsuario) {
    this.codUsuario = codUsuario;
  }

  public Date getFechaOperacion() {
    return this.fechaOperacion;
  }

  public void setFechaOperacion(Date fechaOperacion) {
    this.fechaOperacion = fechaOperacion;
  }

}
