package dev.com.matricula.model;

// Generated 02/02/2014 11:46:24 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ParentescoId generated by hbm2java
 */
public class ParentescoId implements java.io.Serializable {

  private String parentesco;
  private String idApoderado;
  private String idAlumno;
  private Integer codUsuario;
  private Date fechaOperacion;

  public ParentescoId() {
  }

  public ParentescoId(String parentesco, String idApoderado, String idAlumno) {
    this.parentesco = parentesco;
    this.idApoderado = idApoderado;
    this.idAlumno = idAlumno;
  }

  public ParentescoId(String parentesco, String idApoderado, String idAlumno, Integer codUsuario,
          Date fechaOperacion) {
    this.parentesco = parentesco;
    this.idApoderado = idApoderado;
    this.idAlumno = idAlumno;
    this.codUsuario = codUsuario;
    this.fechaOperacion = fechaOperacion;
  }

  public String getParentesco() {
    return this.parentesco;
  }

  public void setParentesco(String parentesco) {
    this.parentesco = parentesco;
  }

  public String getIdApoderado() {
    return this.idApoderado;
  }

  public void setIdApoderado(String idApoderado) {
    this.idApoderado = idApoderado;
  }

  public String getIdAlumno() {
    return this.idAlumno;
  }

  public void setIdAlumno(String idAlumno) {
    this.idAlumno = idAlumno;
  }

  public Integer getCodUsuario() {
    return this.codUsuario;
  }

  public void setCodUsuario(Integer codUsuario) {
    this.codUsuario = codUsuario;
  }

  public Date getFechaOperacion() {
    return this.fechaOperacion;
  }

  public void setFechaOperacion(Date fechaOperacion) {
    this.fechaOperacion = fechaOperacion;
  }

  @Override
  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof ParentescoId))
      return false;
    ParentescoId castOther = (ParentescoId) other;

    return ((this.getParentesco() == castOther.getParentesco()) || (this.getParentesco() != null
            && castOther.getParentesco() != null && this.getParentesco().equals(
            castOther.getParentesco())))
            && ((this.getIdApoderado() == castOther.getIdApoderado()) || (this.getIdApoderado() != null
                    && castOther.getIdApoderado() != null && this.getIdApoderado().equals(
                    castOther.getIdApoderado())))
            && ((this.getIdAlumno() == castOther.getIdAlumno()) || (this.getIdAlumno() != null
                    && castOther.getIdAlumno() != null && this.getIdAlumno().equals(
                    castOther.getIdAlumno())))
            && ((this.getCodUsuario() == castOther.getCodUsuario()) || (this.getCodUsuario() != null
                    && castOther.getCodUsuario() != null && this.getCodUsuario().equals(
                    castOther.getCodUsuario())))
            && ((this.getFechaOperacion() == castOther.getFechaOperacion()) || (this
                    .getFechaOperacion() != null && castOther.getFechaOperacion() != null && this
                    .getFechaOperacion().equals(castOther.getFechaOperacion())));
  }

  @Override
  public int hashCode() {
    int result = 17;

    result = 37 * result + (getParentesco() == null ? 0 : this.getParentesco().hashCode());
    result = 37 * result + (getIdApoderado() == null ? 0 : this.getIdApoderado().hashCode());
    result = 37 * result + (getIdAlumno() == null ? 0 : this.getIdAlumno().hashCode());
    result = 37 * result + (getCodUsuario() == null ? 0 : this.getCodUsuario().hashCode());
    result = 37 * result + (getFechaOperacion() == null ? 0 : this.getFechaOperacion().hashCode());
    return result;
  }

}
