package dev.com.matricula.model;

// Generated 02/02/2014 11:46:24 AM by Hibernate Tools 4.0.0

/**
 * Promedio generated by hbm2java
 */
public class Promedio implements java.io.Serializable {

  private PromedioId id;
  private Curso curso;
  private Alumno alumno;

  public Promedio() {
  }

  public Promedio(PromedioId id, Curso curso, Alumno alumno) {
    this.id = id;
    this.curso = curso;
    this.alumno = alumno;
  }

  public PromedioId getId() {
    return this.id;
  }

  public void setId(PromedioId id) {
    this.id = id;
  }

  public Curso getCurso() {
    return this.curso;
  }

  public void setCurso(Curso curso) {
    this.curso = curso;
  }

  public Alumno getAlumno() {
    return this.alumno;
  }

  public void setAlumno(Alumno alumno) {
    this.alumno = alumno;
  }

}
