package dev.com.matricula.model;

// Generated 02/02/2014 11:46:24 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * PromedioId generated by hbm2java
 */
public class PromedioId implements java.io.Serializable {

  private BigDecimal promedio;
  private String idAlumno;
  private String idCurso;
  private Short codUsuario;
  private Date fechaOperacion;

  public PromedioId() {
  }

  public PromedioId(String idAlumno, String idCurso) {
    this.idAlumno = idAlumno;
    this.idCurso = idCurso;
  }

  public PromedioId(BigDecimal promedio, String idAlumno, String idCurso, Short codUsuario,
          Date fechaOperacion) {
    this.promedio = promedio;
    this.idAlumno = idAlumno;
    this.idCurso = idCurso;
    this.codUsuario = codUsuario;
    this.fechaOperacion = fechaOperacion;
  }

  public BigDecimal getPromedio() {
    return this.promedio;
  }

  public void setPromedio(BigDecimal promedio) {
    this.promedio = promedio;
  }

  public String getIdAlumno() {
    return this.idAlumno;
  }

  public void setIdAlumno(String idAlumno) {
    this.idAlumno = idAlumno;
  }

  public String getIdCurso() {
    return this.idCurso;
  }

  public void setIdCurso(String idCurso) {
    this.idCurso = idCurso;
  }

  public Short getCodUsuario() {
    return this.codUsuario;
  }

  public void setCodUsuario(Short codUsuario) {
    this.codUsuario = codUsuario;
  }

  public Date getFechaOperacion() {
    return this.fechaOperacion;
  }

  public void setFechaOperacion(Date fechaOperacion) {
    this.fechaOperacion = fechaOperacion;
  }

  @Override
  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof PromedioId))
      return false;
    PromedioId castOther = (PromedioId) other;

    return ((this.getPromedio() == castOther.getPromedio()) || (this.getPromedio() != null
            && castOther.getPromedio() != null && this.getPromedio()
            .equals(castOther.getPromedio())))
            && ((this.getIdAlumno() == castOther.getIdAlumno()) || (this.getIdAlumno() != null
                    && castOther.getIdAlumno() != null && this.getIdAlumno().equals(
                    castOther.getIdAlumno())))
            && ((this.getIdCurso() == castOther.getIdCurso()) || (this.getIdCurso() != null
                    && castOther.getIdCurso() != null && this.getIdCurso().equals(
                    castOther.getIdCurso())))
            && ((this.getCodUsuario() == castOther.getCodUsuario()) || (this.getCodUsuario() != null
                    && castOther.getCodUsuario() != null && this.getCodUsuario().equals(
                    castOther.getCodUsuario())))
            && ((this.getFechaOperacion() == castOther.getFechaOperacion()) || (this
                    .getFechaOperacion() != null && castOther.getFechaOperacion() != null && this
                    .getFechaOperacion().equals(castOther.getFechaOperacion())));
  }

  @Override
  public int hashCode() {
    int result = 17;

    result = 37 * result + (getPromedio() == null ? 0 : this.getPromedio().hashCode());
    result = 37 * result + (getIdAlumno() == null ? 0 : this.getIdAlumno().hashCode());
    result = 37 * result + (getIdCurso() == null ? 0 : this.getIdCurso().hashCode());
    result = 37 * result + (getCodUsuario() == null ? 0 : this.getCodUsuario().hashCode());
    result = 37 * result + (getFechaOperacion() == null ? 0 : this.getFechaOperacion().hashCode());
    return result;
  }

}
