package dev.com.matricula.model;

// Generated 28/02/2014 12:15:27 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * Promedio generated by hbm2java
 */
public class Promedio implements java.io.Serializable {

  private int idPromedio;
  private Curso curso;
  private Alumno alumno;
  private BigDecimal promedio;
  private Short codUsuario;
  private Date fechaOperacion;

  public Promedio() {
  }

  public Promedio(int idPromedio, Curso curso, Alumno alumno) {
    this.idPromedio = idPromedio;
    this.curso = curso;
    this.alumno = alumno;
  }

  public Promedio(int idPromedio, Curso curso, Alumno alumno, BigDecimal promedio,
          Short codUsuario, Date fechaOperacion) {
    this.idPromedio = idPromedio;
    this.curso = curso;
    this.alumno = alumno;
    this.promedio = promedio;
    this.codUsuario = codUsuario;
    this.fechaOperacion = fechaOperacion;
  }

  public int getIdPromedio() {
    return this.idPromedio;
  }

  public void setIdPromedio(int idPromedio) {
    this.idPromedio = idPromedio;
  }

  public Curso getCurso() {
    return this.curso;
  }

  public void setCurso(Curso curso) {
    this.curso = curso;
  }

  public Alumno getAlumno() {
    return this.alumno;
  }

  public void setAlumno(Alumno alumno) {
    this.alumno = alumno;
  }

  public BigDecimal getPromedio() {
    return this.promedio;
  }

  public void setPromedio(BigDecimal promedio) {
    this.promedio = promedio;
  }

  public Short getCodUsuario() {
    return this.codUsuario;
  }

  public void setCodUsuario(Short codUsuario) {
    this.codUsuario = codUsuario;
  }

  public Date getFechaOperacion() {
    return this.fechaOperacion;
  }

  public void setFechaOperacion(Date fechaOperacion) {
    this.fechaOperacion = fechaOperacion;
  }

}
