package dev.com.matricula.model;

// Generated 28/02/2014 12:15:27 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol implements java.io.Serializable {

  private int idRol;
  private String descripcion;
  private char estado;
  private Integer codUsuario;
  private Date fechaOperacion;
  private Set rolusuarios = new HashSet(0);

  public Rol() {
  }

  public Rol(int idRol, String descripcion, char estado) {
    this.idRol = idRol;
    this.descripcion = descripcion;
    this.estado = estado;
  }

  public Rol(int idRol, String descripcion, char estado, Integer codUsuario, Date fechaOperacion,
          Set rolusuarios) {
    this.idRol = idRol;
    this.descripcion = descripcion;
    this.estado = estado;
    this.codUsuario = codUsuario;
    this.fechaOperacion = fechaOperacion;
    this.rolusuarios = rolusuarios;
  }

  public int getIdRol() {
    return this.idRol;
  }

  public void setIdRol(int idRol) {
    this.idRol = idRol;
  }

  public String getDescripcion() {
    return this.descripcion;
  }

  public void setDescripcion(String descripcion) {
    this.descripcion = descripcion;
  }

  public char getEstado() {
    return this.estado;
  }

  public void setEstado(char estado) {
    this.estado = estado;
  }

  public Integer getCodUsuario() {
    return this.codUsuario;
  }

  public void setCodUsuario(Integer codUsuario) {
    this.codUsuario = codUsuario;
  }

  public Date getFechaOperacion() {
    return this.fechaOperacion;
  }

  public void setFechaOperacion(Date fechaOperacion) {
    this.fechaOperacion = fechaOperacion;
  }

  public Set getRolusuarios() {
    return this.rolusuarios;
  }

  public void setRolusuarios(Set rolusuarios) {
    this.rolusuarios = rolusuarios;
  }

}
