package dev.com.matricula.model;

// Generated 28/02/2014 12:15:27 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Usuarioalumno generated by hbm2java
 */
public class Usuarioalumno implements java.io.Serializable {

  private int idUsuarioAlumno;
  private int idUsuario;
  private int idAlumno;
  private Integer codUsuario;
  private Date fechaOperacion;

  public Usuarioalumno() {
  }

  public Usuarioalumno(int idUsuarioAlumno, int idUsuario, int idAlumno) {
    this.idUsuarioAlumno = idUsuarioAlumno;
    this.idUsuario = idUsuario;
    this.idAlumno = idAlumno;
  }

  public Usuarioalumno(int idUsuarioAlumno, int idUsuario, int idAlumno, Integer codUsuario,
          Date fechaOperacion) {
    this.idUsuarioAlumno = idUsuarioAlumno;
    this.idUsuario = idUsuario;
    this.idAlumno = idAlumno;
    this.codUsuario = codUsuario;
    this.fechaOperacion = fechaOperacion;
  }

  public int getIdUsuarioAlumno() {
    return this.idUsuarioAlumno;
  }

  public void setIdUsuarioAlumno(int idUsuarioAlumno) {
    this.idUsuarioAlumno = idUsuarioAlumno;
  }

  public int getIdUsuario() {
    return this.idUsuario;
  }

  public void setIdUsuario(int idUsuario) {
    this.idUsuario = idUsuario;
  }

  public int getIdAlumno() {
    return this.idAlumno;
  }

  public void setIdAlumno(int idAlumno) {
    this.idAlumno = idAlumno;
  }

  public Integer getCodUsuario() {
    return this.codUsuario;
  }

  public void setCodUsuario(Integer codUsuario) {
    this.codUsuario = codUsuario;
  }

  public Date getFechaOperacion() {
    return this.fechaOperacion;
  }

  public void setFechaOperacion(Date fechaOperacion) {
    this.fechaOperacion = fechaOperacion;
  }

}
