package dev.com.matricula.model;

// Generated 28/02/2014 12:15:27 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

  private int idUsuario;
  private String nombre;
  private String apPaterno;
  private String apMaterno;
  private String dni;
  private String login;
  private String clave;
  private char estado;
  private Integer codUsuario;
  private Date fechaOperacion;
  private Set rolUsuarios = new HashSet(0);

  public Usuario() {
  }

  public Usuario(int idUsuario, String nombre, String apPaterno, String apMaterno, String dni,
          String login, String clave, char estado) {
    this.idUsuario = idUsuario;
    this.nombre = nombre;
    this.apPaterno = apPaterno;
    this.apMaterno = apMaterno;
    this.dni = dni;
    this.login = login;
    this.clave = clave;
    this.estado = estado;
  }

  public Usuario(int idUsuario, String nombre, String apPaterno, String apMaterno, String dni,
          String login, String clave, char estado, Integer codUsuario, Date fechaOperacion,
          Set rolUsuarios) {
    this.idUsuario = idUsuario;
    this.nombre = nombre;
    this.apPaterno = apPaterno;
    this.apMaterno = apMaterno;
    this.dni = dni;
    this.login = login;
    this.clave = clave;
    this.estado = estado;
    this.codUsuario = codUsuario;
    this.fechaOperacion = fechaOperacion;
    this.rolUsuarios = rolUsuarios;
  }

  public int getIdUsuario() {
    return this.idUsuario;
  }

  public void setIdUsuario(int idUsuario) {
    this.idUsuario = idUsuario;
  }

  public String getNombre() {
    return this.nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public String getApPaterno() {
    return this.apPaterno;
  }

  public void setApPaterno(String apPaterno) {
    this.apPaterno = apPaterno;
  }

  public String getApMaterno() {
    return this.apMaterno;
  }

  public void setApMaterno(String apMaterno) {
    this.apMaterno = apMaterno;
  }

  public String getDni() {
    return this.dni;
  }

  public void setDni(String dni) {
    this.dni = dni;
  }

  public String getLogin() {
    return this.login;
  }

  public void setLogin(String login) {
    this.login = login;
  }

  public String getClave() {
    return this.clave;
  }

  public void setClave(String clave) {
    this.clave = clave;
  }

  public char getEstado() {
    return this.estado;
  }

  public void setEstado(char estado) {
    this.estado = estado;
  }

  public Integer getCodUsuario() {
    return this.codUsuario;
  }

  public void setCodUsuario(Integer codUsuario) {
    this.codUsuario = codUsuario;
  }

  public Date getFechaOperacion() {
    return this.fechaOperacion;
  }

  public void setFechaOperacion(Date fechaOperacion) {
    this.fechaOperacion = fechaOperacion;
  }

  public Set getRolUsuarios() {
    return this.rolUsuarios;
  }

  public void setRolUsuarios(Set rolUsuarios) {
    this.rolUsuarios = rolUsuarios;
  }

}
