package dev.com.matricula.model;

// Generated 28/02/2014 12:15:27 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Usuariodocente generated by hbm2java
 */
public class Usuariodocente implements java.io.Serializable {

  private int idUsuarioDocente;
  private int idUsuario;
  private int idDocente;
  private Integer codUsuario;
  private Date fechaOperacion;

  public Usuariodocente() {
  }

  public Usuariodocente(int idUsuarioDocente, int idUsuario, int idDocente) {
    this.idUsuarioDocente = idUsuarioDocente;
    this.idUsuario = idUsuario;
    this.idDocente = idDocente;
  }

  public Usuariodocente(int idUsuarioDocente, int idUsuario, int idDocente, Integer codUsuario,
          Date fechaOperacion) {
    this.idUsuarioDocente = idUsuarioDocente;
    this.idUsuario = idUsuario;
    this.idDocente = idDocente;
    this.codUsuario = codUsuario;
    this.fechaOperacion = fechaOperacion;
  }

  public int getIdUsuarioDocente() {
    return this.idUsuarioDocente;
  }

  public void setIdUsuarioDocente(int idUsuarioDocente) {
    this.idUsuarioDocente = idUsuarioDocente;
  }

  public int getIdUsuario() {
    return this.idUsuario;
  }

  public void setIdUsuario(int idUsuario) {
    this.idUsuario = idUsuario;
  }

  public int getIdDocente() {
    return this.idDocente;
  }

  public void setIdDocente(int idDocente) {
    this.idDocente = idDocente;
  }

  public Integer getCodUsuario() {
    return this.codUsuario;
  }

  public void setCodUsuario(Integer codUsuario) {
    this.codUsuario = codUsuario;
  }

  public Date getFechaOperacion() {
    return this.fechaOperacion;
  }

  public void setFechaOperacion(Date fechaOperacion) {
    this.fechaOperacion = fechaOperacion;
  }

}
